#!/bin/bash
#add the source from log.sh
source log.sh

# Function to perform search file by name or extension
search_file() {

    # Initialize variables
    DIRECTORY=""
    FILENAME=""
    EXTENSION=""

    # Parse command-line options
    while getopts "d:n:e:" opt; do
        case "$opt" in
            d) DIRECTORY="$OPTARG";;
            n) FILENAME="$OPTARG";;
            e) EXTENSION="$OPTARG";;
            *) echo "Invalid option"; exit 1;;
        esac
    done

    # Check if the directory exists
    if [ ! -d "$DIRECTORY" ]; then
        echo "ERROR: Invalid directory: $DIRECTORY"
        log_action "ERROR: Invalid directory: $DIRECTORY"
        exit 1
    fi

    # Search file by name if provided
    if [ -n "$FILENAME" ]; then
        log_action "Searching for file by name: $FILENAME in $DIRECTORY"
        find "$DIRECTORY" -type f -name "$FILENAME"

    # Search files by extension if provided
    elif [ -n "$EXTENSION" ]; then
        log_action "Searching for files with extension .$EXTENSION in $DIRECTORY"
        find "$DIRECTORY" -type f -name "*.$EXTENSION"

    else
        # If no filename or extension is provided, output an error
        echo "ERROR: You must provide either a filename or an extension."
        log_action "ERROR: No filename or extension provided."
        exit 1
    fi
}
# Call the function with arguments passed to the script
search_file "$@"

